import NavigationDrawer from "../components/navigation/NavigationDrawer";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let loggedIn = true;
  if (loggedIn) {
    return (
      <html lang="en">
        <body>
          <NavigationDrawer children={children}/>
        </body>
      </html>
    );
  }
  else {
    return <div>login page</div>
  }
  
}
